# Generated by Django 4.0.1 on 2022-04-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='annual_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroseao', models.CharField(max_length=100, null=True)),
                ('numero', models.CharField(max_length=100, null=True)),
                ('organisme', models.CharField(max_length=100, null=True)),
                ('municipal', models.CharField(max_length=2, null=True)),
                ('adresse1', models.CharField(max_length=100, null=True)),
                ('adresse2', models.CharField(max_length=100, null=True)),
                ('ville', models.CharField(max_length=20, null=True)),
                ('province', models.CharField(max_length=50, null=True)),
                ('pays', models.CharField(max_length=5, null=True)),
                ('codepostal', models.CharField(max_length=100, null=True)),
                ('titre', models.TextField(null=True)),
                ('type', models.CharField(max_length=5, null=True)),
                ('nature', models.CharField(max_length=5, null=True)),
                ('precision', models.CharField(max_length=100, null=True)),
                ('categorieseao', models.CharField(max_length=100, null=True)),
                ('datepublication', models.DateField(null=True)),
                ('datefermeture', models.DateField(null=True)),
                ('datesaisieouverture', models.DateField(null=True)),
                ('datesaisieadjudication', models.DateField(null=True)),
                ('dateadjudication', models.DateField(null=True)),
                ('regionlivraison', models.TextField(null=True)),
                ('unspscprincipale', models.IntegerField(null=True)),
                ('disposition', models.IntegerField(null=True)),
                ('hyperlienseao', models.TextField(null=True)),
                ('fournisseur_nomorganisation', models.CharField(max_length=100, null=True)),
                ('fournisseur_adresse1', models.CharField(max_length=100, null=True)),
                ('fournisseur_adresse2', models.CharField(max_length=100, null=True)),
                ('fournisseur_ville', models.CharField(max_length=100, null=True)),
                ('fournisseur_province', models.CharField(max_length=100, null=True)),
                ('fournisseur_pays', models.CharField(max_length=100, null=True)),
                ('fournisseur_codepostal', models.TextField(null=True)),
                ('fournisseur_neq', models.IntegerField(null=True)),
                ('fournisseur_admissible', models.IntegerField(null=True)),
                ('fournisseur_conforme', models.IntegerField(null=True)),
                ('fournisseur_adjudicataire', models.IntegerField(null=True)),
                ('fournisseur_montantsoumis', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fournisseur_montantssoumisunite', models.IntegerField(null=True)),
                ('fournisseur_montantcontrat', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fournisseur_montanttotalcontrat', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'annual_data',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=100)),
                ('user_last_name', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='weekly_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('party_0_name', models.CharField(max_length=100, null=True)),
                ('party_0_address_locality', models.CharField(max_length=500, null=True)),
                ('party_1_name', models.CharField(max_length=100, null=True)),
                ('party_1_role', models.CharField(max_length=100, null=True)),
                ('party_1_details_NEQ', models.CharField(max_length=100, null=True)),
                ('buyer_name', models.CharField(max_length=200, null=True)),
                ('tender_title', models.TextField(null=True)),
                ('tender_items_classification_description', models.TextField(null=True)),
                ('tender_procurement_Method', models.CharField(max_length=100, null=True)),
                ('tender_procurement_Method_Details', models.CharField(max_length=100, null=True)),
                ('tender_additional_Procurement_Categories', models.CharField(max_length=100, null=True)),
                ('tender_tenderer_name', models.TextField(null=True)),
                ('awards_date', models.DateField(null=True)),
                ('awards_value_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('contracts_value_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'weekly_data',
            },
        ),
    ]
