# Generated by Django 4.0.1 on 2022-04-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seao_connect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekly_data',
            name='party_0_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='weekly_data',
            name='party_1_details_NEQ',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='weekly_data',
            name='party_1_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='weekly_data',
            name='party_1_role',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='weekly_data',
            name='tender_additional_Procurement_Categories',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='weekly_data',
            name='tender_procurement_Method',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='weekly_data',
            name='tender_procurement_Method_Details',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
